/**
 * Booking types and store. Uses Supabase when configured, else in-memory (dev fallback).
 */
import { createHash } from "node:crypto";
import { getSupabase, hasSupabase } from "./supabase";

export type BookingStatus = "pending" | "confirmed" | "cancelled";
export type BookingType = "winery_tasting" | "guide_tour";
export type Booking = {
  id: string; type: BookingType; providerId: string; providerName: string; date: string;
  partySize: number; guestEmail: string; guestName: string; status: BookingStatus;
  createdAt: string; notes?: string;
};
const memoryStore: Booking[] = [];
export class BookingIdempotencyConflictError extends Error { constructor(){ super("The idempotency key was already used for a different booking request."); this.name="BookingIdempotencyConflictError"; } }
function idForIdempotencyKey(key:string,email:string){ return `b-idem-${createHash("sha256").update(`${email}\0${key}`).digest("hex")}`; }
function matchesBookingRequest(existing:Booking,input:Omit<Booking,"id"|"status"|"createdAt">,email:string){ return existing.type===input.type&&existing.providerId===input.providerId&&existing.providerName===input.providerName&&existing.date===input.date&&existing.partySize===input.partySize&&existing.guestEmail===email&&existing.guestName===input.guestName&&(existing.notes??undefined)===(input.notes??undefined); }
function replayOrThrow(existing:Booking,input:Omit<Booking,"id"|"status"|"createdAt">,email:string):CreateBookingResult{ if(!matchesBookingRequest(existing,input,email)) throw new BookingIdempotencyConflictError(); return {booking:existing,created:false}; }
export type CreateBookingInput=Omit<Booking,"id"|"status"|"createdAt">&{leadFeeEur?:number;idempotencyKey:string};
export type CreateBookingResult={booking:Booking;created:boolean};
export async function createBooking(input:CreateBookingInput):Promise<CreateBookingResult>{ const {leadFeeEur,idempotencyKey,...rest}=input; const email=input.guestEmail.trim().toLowerCase(); const id=idForIdempotencyKey(idempotencyKey,email); const createdAt=new Date().toISOString(); const booking:Booking={...rest,guestEmail:email,id,status:"pending",createdAt}; const supabase=getSupabase(); if(supabase){ const {data:existing,error:lookupError}=await supabase.from("bookings").select("*").eq("id",id).maybeSingle(); if(lookupError)throw new Error(lookupError.message); if(existing)return replayOrThrow(rowToBooking(existing as Record<string,unknown>),rest,email); const {error}=await supabase.from("bookings").insert({id,type:input.type,provider_id:input.providerId,provider_name:input.providerName,date:input.date,party_size:input.partySize,guest_email:email,guest_name:input.guestName,status:"pending",notes:input.notes??null,created_at:createdAt,lead_fee_eur:leadFeeEur??null}); if(error){if(error.code==="23505"){const {data:replayed}=await supabase.from("bookings").select("*").eq("id",id).maybeSingle();if(replayed)return replayOrThrow(rowToBooking(replayed as Record<string,unknown>),rest,email);}throw new Error(error.message);}return{booking,created:true}; } const existing=memoryStore.find(x=>x.id===id);if(existing)return replayOrThrow(existing,rest,email);memoryStore.push(booking);return{booking,created:true}; }
export async function getBookingsByEmail(email:string):Promise<Booking[]>{const supabase=getSupabase();const normalized=email.trim().toLowerCase();if(supabase){const {data,error}=await supabase.from("bookings").select("id,type,provider_id,provider_name,date,party_size,guest_email,guest_name,status,created_at,notes").eq("guest_email",normalized).order("created_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(r=>rowToBooking(r as Record<string,unknown>));}return memoryStore.filter(b=>b.guestEmail.toLowerCase()===normalized).sort((a,b)=>b.createdAt>a.createdAt?1:-1);}
export async function getBookingsByProviderId(providerId:string):Promise<Booking[]>{const supabase=getSupabase();if(supabase){const {data,error}=await supabase.from("bookings").select("id,type,provider_id,provider_name,date,party_size,guest_email,guest_name,status,created_at,notes").eq("provider_id",providerId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(r=>rowToBooking(r as Record<string,unknown>));}return memoryStore.filter(b=>b.providerId===providerId).sort((a,b)=>b.createdAt>a.createdAt?1:-1);}
export async function updateBookingStatus(id:string,status:BookingStatus,providerId:string):Promise<{booking:Booking}|{error:"not_found"|"forbidden"}>{if(status!=="confirmed"&&status!=="cancelled")return{error:"not_found"};const supabase=getSupabase();if(supabase){const {data:existing,error:lookupError}=await supabase.from("bookings").select("*").eq("id",id).maybeSingle();if(lookupError)throw new Error(lookupError.message);if(!existing)return{error:"not_found"};const current=rowToBooking(existing as Record<string,unknown>);if(current.providerId!==providerId)return{error:"forbidden"};if(current.status!=="pending")return{error:"not_found"};const {data:updated,error}=await supabase.from("bookings").update({status}).eq("id",id).eq("provider_id",providerId).eq("status","pending").select("*").maybeSingle();if(error)throw new Error(error.message);if(!updated)return{error:"not_found"};return{booking:rowToBooking(updated as Record<string,unknown>)};}const current=memoryStore.find(b=>b.id===id);if(!current)return{error:"not_found"};if(current.providerId!==providerId)return{error:"forbidden"};if(current.status!=="pending")return{error:"not_found"};current.status=status;return{booking:current};}
function rowToBooking(row:Record<string,unknown>):Booking{const type=row.type==="guide_tour"?"guide_tour":"winery_tasting";return{id:String(row.id),type,providerId:String(row.provider_id),providerName:String(row.provider_name),date:String(row.date),partySize:Number(row.party_size),guestEmail:String(row.guest_email),guestName:String(row.guest_name),status:(row.status as BookingStatus)??"pending",createdAt:String(row.created_at),notes:row.notes?String(row.notes):undefined};}
export async function getBookingsCountThisMonth(){return getBookingsCountSince(getMonthStart());}function getMonthStart(){const start=new Date();start.setDate(1);start.setHours(0,0,0,0);return start;}export async function getBookingsCountSince(start:Date){return getBookingsCountInRange(start);}export async function getBookingsCountInRange(start:Date,end?:Date){const supabase=getSupabase();const startIso=start.toISOString();const endIso=end?.toISOString();if(supabase){let query=supabase.from("bookings").select("*",{count:"exact",head:true}).gte("created_at",startIso);if(endIso)query=query.lt("created_at",endIso);const {count,error}=await query;if(error)return 0;return count??0;}const ws=start.getTime(),we=end?.getTime();return memoryStore.filter(b=>{const created=new Date(b.createdAt).getTime();return created>=ws&&(typeof we!=="number"||created<we);}).length;}
export const useDb=hasSupabase;
