/**
 * Regenerate src/data/plan-items.generated.ts — the lean PlanItem index the
 * app shell uses for plan resolution (id, name, region, type + trail slug
 * aliases). Keeping this as a checked-in projection lets useItinerary and the
 * share/ICS libs avoid value-importing the full @/data barrel (~252KB of
 * client JS on every page). Guarded by src/data/plan-items.generated.test.ts.
 *
 * Run: npm run data:plan-items
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allPlaces } from "../../src/data";
import { trails } from "../../src/data/trails";

const OUT = join(process.cwd(), "src/data/plan-items.generated.ts");

const slugAliases = trails
  .filter((t) => t.slug && t.slug !== t.id)
  .map((t) => [t.slug, t.id] as const);

const header = `/**
 * AUTO-GENERATED by \`npm run data:plan-items\` — do not edit by hand.
 * Lean PlanItem projection of every bookable/plannable place, plus trail
 * slug aliases. The sync test fails if this drifts from @/data.
 */
import type { PlanItem } from "@/data";
`;

const items = `export const PLAN_ITEMS: PlanItem[] = ${JSON.stringify(allPlaces, null, 2)};\n`;
const aliases = `export const TRAIL_SLUG_TO_ID: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(slugAliases),
  null,
  2
)};\n`;

writeFileSync(OUT, `${header}\n${items}\n${aliases}`, "utf8");
console.log(
  `plan-items.generated.ts: ${allPlaces.length} items, ${slugAliases.length} slug aliases`
);
