/**
 * AUTO-GENERATED by `npm run data:plan-items` — do not edit by hand.
 * Lean PlanItem projection of every bookable/plannable place, plus trail
 * slug aliases. The sync test fails if this drifts from @/data.
 */
import type { PlanItem } from "@/data";

export const PLAN_ITEMS: PlanItem[] = [
  {
    "id": "nissi-beach",
    "name": "Nissi Beach",
    "nameEl": "Παραλία Νησί",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "fig-tree-bay",
    "name": "Fig Tree Bay",
    "nameEl": "Παραλία Συκιά",
    "region": "Protaras",
    "type": "attraction"
  },
  {
    "id": "konnos-bay",
    "name": "Konnos Bay",
    "nameEl": "Κόλπος Κόννος",
    "region": "Cape Greco",
    "type": "attraction"
  },
  {
    "id": "coral-bay",
    "name": "Coral Bay",
    "nameEl": "Παραλία Κοραλ",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "lara-bay",
    "name": "Lara Bay",
    "nameEl": "Παραλία Λάρα",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "ayia-napa-sea-caves",
    "name": "Sea Caves",
    "nameEl": "Θαλάσσιες Σπηλιές",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "governors-beach",
    "name": "Governor's Beach",
    "nameEl": "Παραλία Κυβερνήτη",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "limassol-marina",
    "name": "Limassol Marina",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "larnaca-aliki",
    "name": "Larnaca Salt Lake",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "gerakopetra-boulders",
    "name": "Gerakopetra (Ineia Crag)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "droushia-konefti-boulders",
    "name": "Droushia & Konefti Boulders",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "klirou-boulders",
    "name": "Klirou Valley Boulders",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "arakapas-boulders",
    "name": "Arakapas Boulders",
    "region": "Pitsilia",
    "type": "attraction"
  },
  {
    "id": "climb-cyprus-limassol",
    "name": "Climb Cyprus (Indoor)",
    "region": "Limassol",
    "type": "activity"
  },
  {
    "id": "cape-greco-climbing",
    "name": "Cape Greco Cliffs",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "petra-tou-romiou-cliffs",
    "name": "Petra tou Romiou Cliffs",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "troodos-cycling-hub",
    "name": "Troodos Cycling Routes",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "akamas-latchi-cycling",
    "name": "Akamas & Latchi Cycling",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "limassol-coastal-cycle",
    "name": "Limassol Coastal Cycle Path",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "latchi-kayak-base",
    "name": "Latchi Harbour & Kayak",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "zenobia-diving",
    "name": "Zenobia Wreck (Diving)",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "cape-greco-kayak",
    "name": "Cape Greco Sea Caves (Kayak)",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "lady-mile-windsurf",
    "name": "Lady's Mile Windsurfing",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "ayii-anargyri-spa",
    "name": "Ayii Anargyri Natural Healing Spa",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kourion-coastal-scramble",
    "name": "Kourion Sea Cliffs",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "white-rocks-paphos",
    "name": "White Rocks (Agios Georgios)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "prodromos-dam-cycling",
    "name": "Prodromos Dam & Forest Roads",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "krasochoria-gravel-loop",
    "name": "Krasochoria Gravel Loop",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "pomos-harbour-coast",
    "name": "Pomos Harbour & Tylliria Coast",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "germasogeia-dam-paddle",
    "name": "Germasogeia Dam Paddle",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "tzelefos-bridge",
    "name": "Tzelefos Venetian Bridge",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "episkopi-crags",
    "name": "Episkopi (Paphos) Crags",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "episkopi-boulders",
    "name": "Episkopi Boulders (Paphos)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kellaki-kyparissia-ridge",
    "name": "Kyparissia Ridge (Kellaki)",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "trimiklini-dam-cycling",
    "name": "Trimiklini Dam Roads",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "xyliatos-dam-cycle",
    "name": "Xyliatos Dam & Peristerona Loop",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "green-bay-protaras",
    "name": "Green Bay (Protaras)",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "pissouri-bay-coast",
    "name": "Pissouri Bay Coast",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "kannavia-forest-bathing",
    "name": "Kannavia Forest Trails",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "amphorae-caves-paphos",
    "name": "Amphorae Caves (Moulia)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "amiantos-geopark",
    "name": "Troodos Geopark (Amiantos)",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "mesa-potamos-grove",
    "name": "Mesa Potamos Picnic Grove",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "pitsilia-cycling-loop",
    "name": "Pitsilia Village Loop",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "minthis-forest-paphos",
    "name": "Minthis Forest (Paphos Hills)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "potamia-dam-cycling",
    "name": "Potamia Dam & Laxia Loop",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "paramali-coast",
    "name": "Paramali & West Limassol Coast",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "silikou-valley-trail",
    "name": "Silikou Commandaria Valley",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "cape-greco-cyclops-dive",
    "name": "Cyclops Cave (Cape Greco)",
    "region": "Ayia Napa",
    "type": "attraction"
  },
  {
    "id": "eptagoneia-limestone-boulders",
    "name": "Eptagoneia Boulders",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "larnaca-village-coastal-cycle",
    "name": "Orange Valley & Zygi Coastal Loop",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "mackenzie-larnaca-coast",
    "name": "Mackenzie Beach & Larnaca Bay",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "athalassa-forest-park",
    "name": "Athalassa National Forest Park",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "pafos-mosaics",
    "name": "Pafos Archaeological Site",
    "nameEl": "Πάφος",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kourion",
    "name": "Kourion",
    "nameEl": "Κούριον",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "tomb-of-kings",
    "name": "Tombs of the Kings",
    "nameEl": "Τάφοι των Βασιλέων",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "salamis",
    "name": "Salamis",
    "nameEl": "Σαλαμίνα",
    "region": "Famagusta",
    "type": "attraction"
  },
  {
    "id": "st-hilarion",
    "name": "St Hilarion Castle",
    "nameEl": "Κάστρο Αγίου Ιλαρίωνα",
    "region": "Kyrenia",
    "type": "attraction"
  },
  {
    "id": "amahti",
    "name": "Amathus",
    "nameEl": "Αμαθούς",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "choirokoitia",
    "name": "Choirokoitia",
    "nameEl": "Χοιροκοιτία",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "kolossi",
    "name": "Kolossi Castle",
    "nameEl": "Κόλοσσι",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "palaipafos",
    "name": "Palaipafos (Kouklia)",
    "nameEl": "Παλαίπαφος (Κούκλια)",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "buffavento",
    "name": "Buffavento Castle",
    "nameEl": "Μπουφαβέντο",
    "region": "Kyrenia",
    "type": "attraction"
  },
  {
    "id": "cyprus-museum",
    "name": "Cyprus Museum",
    "nameEl": "Κυπριακό Μουσείο",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "bellapais",
    "name": "Bellapais Abbey",
    "nameEl": "Μπελαπάις",
    "region": "Kyrenia",
    "type": "attraction"
  },
  {
    "id": "leventis-museum",
    "name": "Leventis Municipal Museum",
    "nameEl": "Μουσείο Λεβέντη",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "paphos-castle",
    "name": "Paphos Castle",
    "nameEl": "Κάστρο Πάφου",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "angeloktisti",
    "name": "Angeloktisti (Kiti)",
    "nameEl": "Αγγελόκτιστη",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "idalion",
    "name": "Ancient Idalion",
    "nameEl": "Ιδάλιον",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "kition",
    "name": "Ancient Kition",
    "nameEl": "Κίτιον",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "kalopanagiotis",
    "name": "Kalopanagiotis",
    "nameEl": "Καλοπαναγιώτης",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "lefkara",
    "name": "Lefkara",
    "nameEl": "Λεύκαρα",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "polis",
    "name": "Polis Chrysochous",
    "nameEl": "Πόλις Χρυσοχούς",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "omodos",
    "name": "Omodos",
    "nameEl": "Όμοδος",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "kakopetria",
    "name": "Kakopetria",
    "nameEl": "Κακοπετριά",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "lania",
    "name": "Lania",
    "nameEl": "Λάνια",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "lefke",
    "name": "Lefke",
    "nameEl": "Λεύκα",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "foini",
    "name": "Foini",
    "nameEl": "Φοινί",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "pedoulas",
    "name": "Pedoulas",
    "nameEl": "Πεδουλάς",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "platres",
    "name": "Platres",
    "nameEl": "Πλάτρες",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "pera-pedi",
    "name": "Pera Pedi",
    "nameEl": "Πέρα Πέδι",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "agros",
    "name": "Agros",
    "nameEl": "Αγρός",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "fikardou",
    "name": "Fikardou",
    "nameEl": "Φυκάρδου",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "koilani",
    "name": "Koilani",
    "nameEl": "Κοίλανη",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "lefkara-kato",
    "name": "Kato Lefkara",
    "nameEl": "Κάτω Λεύκαρα",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "vavla",
    "name": "Vavla",
    "nameEl": "Βαυλά",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "galata",
    "name": "Galata",
    "nameEl": "Γαλάτα",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "zodiakos",
    "name": "Zodiakos",
    "nameEl": "Ζωδιακός",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kato-drys",
    "name": "Kato Drys",
    "nameEl": "Κάτω Δρύς",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "louvaras",
    "name": "Louvaras",
    "nameEl": "Λούβαρας",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "lofou",
    "name": "Lofou",
    "nameEl": "Λόφου",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "kampi-farmaka",
    "name": "Kampi Farmaka",
    "nameEl": "Κάμπη του Φαρμάκα",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "koili",
    "name": "Koili",
    "nameEl": "Κοίλι",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kritou-terra",
    "name": "Kritou Terra",
    "nameEl": "Κρήτου Τέρρα",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kormakitis",
    "name": "Kormakitis",
    "nameEl": "Κορμακίτης",
    "region": "Kyrenia",
    "type": "attraction"
  },
  {
    "id": "tochni",
    "name": "Tochni",
    "nameEl": "Τόχνη",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "droushia",
    "name": "Droushia",
    "nameEl": "Δρούσια",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "ineia",
    "name": "Ineia",
    "nameEl": "Ίνεια",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "prodromos",
    "name": "Prodromos",
    "nameEl": "Προδρόμος",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "milia",
    "name": "Milia",
    "nameEl": "Μηλιά",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "spilia",
    "name": "Spilia",
    "nameEl": "Σπήλια",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "pelathousa",
    "name": "Pelathousa",
    "nameEl": "Πελαθούσα",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "trimiklini",
    "name": "Trimiklini",
    "nameEl": "Τριμίκλινι",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "moutoullas",
    "name": "Moutoullas",
    "nameEl": "Μουτουλλάς",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "statos-agios-fotios",
    "name": "Statos–Agios Fotios",
    "nameEl": "Στατός–Άγιος Φώτιος",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "nikitari",
    "name": "Nikitari",
    "nameEl": "Νικητάρι",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "kato-platres",
    "name": "Kato Platres",
    "nameEl": "Κάτω Πλάτρες",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "vretsia",
    "name": "Vretsia",
    "nameEl": "Βρέτσια",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "kellaki",
    "name": "Kellaki (Prastio)",
    "nameEl": "Κελλάκι",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "kannavia",
    "name": "Kannavia",
    "nameEl": "Κανναβιά",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "doros",
    "name": "Doros",
    "nameEl": "Δωρός",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "monagri-village",
    "name": "Monagri",
    "nameEl": "Μονάγρι",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "silikou",
    "name": "Silikou",
    "nameEl": "Συλίκου",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "polystipos",
    "name": "Polystipos",
    "nameEl": "Πολύστυπος",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "alona",
    "name": "Alona",
    "nameEl": "Άλωνα",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "apsiou",
    "name": "Apsiou",
    "nameEl": "Αψιού",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "amiantos",
    "name": "Amiantos",
    "nameEl": "Αμίαντος",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "kalavasos",
    "name": "Kalavasos",
    "nameEl": "Καλαβασός",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "peristerona",
    "name": "Peristerona",
    "nameEl": "Περιστερώνα",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "lagoudera",
    "name": "Lagoudera",
    "nameEl": "Λαγουδερά",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "mitsero",
    "name": "Mitsero",
    "nameEl": "Μιτσερό",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "kykkos",
    "name": "Kykkos Monastery",
    "nameEl": "Ιερά Μονή Κύκκου",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "st-neophytos",
    "name": "Agios Neophytos Monastery",
    "nameEl": "Μονή Αγίου Νεοφύτου",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "trooditissa",
    "name": "Trooditissa Monastery",
    "nameEl": "Μονή Τροοδίτισσας",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "machairas",
    "name": "Machairas Monastery",
    "nameEl": "Ιερά Μονή Μαχαιρά",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "chrysorrogiatissa",
    "name": "Chrysorrogiatissa Monastery",
    "nameEl": "Ιερά Μονή Χρυσορρογιάτισσας",
    "region": "Paphos",
    "type": "attraction"
  },
  {
    "id": "st-john-lampadistis",
    "name": "Agios Ioannis Lampadistis",
    "nameEl": "Άγιος Ιωάννης ο Λαμπαδιστής",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "panagia-tou-araka",
    "name": "Panagia tou Araka",
    "nameEl": "Παναγία του Άρακος",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "st-george-alamanou",
    "name": "Agios Georgios Alamanou",
    "nameEl": "Αγιος Γεώργιος Αλαμάνου",
    "region": "Limassol",
    "type": "attraction"
  },
  {
    "id": "stavrovouni",
    "name": "Stavrovouni Monastery",
    "nameEl": "Σταυροβούνι",
    "region": "Larnaca",
    "type": "attraction"
  },
  {
    "id": "archangelos-michail",
    "name": "Archangelos Michail (Pedoulas)",
    "nameEl": "Άγιος Μιχαήλ Αρχάγγελος",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "st-nicholas-roof",
    "name": "Agios Nikolaos tis Stegis",
    "nameEl": "Άγιος Νικόλαος της Στέγης",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "panagia-tou-moutoulla",
    "name": "Panagia tou Moutoulla",
    "nameEl": "Παναγία του Μουτουλλά",
    "region": "Troodos",
    "type": "attraction"
  },
  {
    "id": "panagia-asinou",
    "name": "Panagia tis Asinou",
    "nameEl": "Παναγία της Ασίνου",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "st-sozomenos",
    "name": "Agios Sozomenos",
    "nameEl": "Άγιος Σωζόμενος",
    "region": "Nicosia",
    "type": "attraction"
  },
  {
    "id": "tsiakkas",
    "name": "Tsiakkas Winery",
    "region": "Pelendri (Limassol)",
    "type": "winery"
  },
  {
    "id": "vouni-panayia",
    "name": "Vouni Panayia Winery",
    "region": "Panayia (Paphos)",
    "type": "winery"
  },
  {
    "id": "zambartas",
    "name": "Zambartas Wineries",
    "region": "Agios Amvrosios (Limassol)",
    "type": "winery"
  },
  {
    "id": "kolios",
    "name": "Kolios Winery",
    "region": "Statos-Ayios Fotios (Paphos)",
    "type": "winery"
  },
  {
    "id": "kyperounta",
    "name": "Kyperounta Winery",
    "region": "Kyperounta (Troodos)",
    "type": "winery"
  },
  {
    "id": "tsangarides",
    "name": "Tsangarides Winery",
    "region": "Lemona (Paphos)",
    "type": "winery"
  },
  {
    "id": "fikardos",
    "name": "Fikardos Winery",
    "region": "Mesogi / Stroumbi (Paphos)",
    "type": "winery"
  },
  {
    "id": "vlassides",
    "name": "Domaine Vlassides",
    "region": "Koilani (Limassol)",
    "type": "winery"
  },
  {
    "id": "vasilikon",
    "name": "Vasilikon Winery",
    "region": "Kathikas (Paphos)",
    "type": "winery"
  },
  {
    "id": "ayia-mavri",
    "name": "Ayia Mavri Winery",
    "region": "Koilani (Limassol)",
    "type": "winery"
  },
  {
    "id": "ezousa",
    "name": "Ezousa Winery",
    "region": "Kannaviou (Paphos)",
    "type": "winery"
  },
  {
    "id": "hadjipavlou",
    "name": "Hadjipavlou Winery",
    "region": "Pera Pedi (Limassol)",
    "type": "winery"
  },
  {
    "id": "aes-ambelis",
    "name": "Aes Ambelis Winery",
    "region": "Kalo Chorio Orinis (Nicosia)",
    "type": "winery"
  },
  {
    "id": "makarounas",
    "name": "Makarounas Winery",
    "region": "Letymbou (Paphos)",
    "type": "winery"
  },
  {
    "id": "minous",
    "name": "Minous Winery",
    "region": "Pachna (Limassol)",
    "type": "winery"
  },
  {
    "id": "christoudia",
    "name": "Christoudia Winery",
    "region": "Kato Drys (Larnaca)",
    "type": "winery"
  },
  {
    "id": "ayii-anargyri",
    "name": "Ayii Anargyri Winery",
    "region": "Miliou (Paphos)",
    "type": "winery"
  },
  {
    "id": "argyrides",
    "name": "Argyrides Winery",
    "region": "Vasa Koilaniou (Limassol)",
    "type": "winery"
  },
  {
    "id": "kalamos",
    "name": "Kalamos Winery",
    "region": "Amargeti (Paphos)",
    "type": "winery"
  },
  {
    "id": "avakas",
    "name": "Avakas Winery",
    "region": "Statos (Paphos)",
    "type": "winery"
  },
  {
    "id": "domes-sergiou",
    "name": "Dómes Sergiou",
    "region": "Skarinou (Larnaca)",
    "type": "winery"
  },
  {
    "id": "mystes",
    "name": "Mystes Winery",
    "region": "Pano Archimandrita (Paphos)",
    "type": "winery"
  },
  {
    "id": "oenou-yi",
    "name": "Oenou Yi Winery",
    "region": "Omodos (Limassol)",
    "type": "winery"
  },
  {
    "id": "sterna-boutique",
    "name": "Sterna Boutique Winery & Museum",
    "region": "Kathikas (Paphos)",
    "type": "winery"
  },
  {
    "id": "silikou-museum",
    "name": "Silikou Commandaria Museum",
    "region": "Silikou (Limassol)",
    "type": "winery"
  },
  {
    "id": "hadjicharalambous",
    "name": "Hadjicharalambous Boutique Winery",
    "region": "Stroumbi (Paphos)",
    "type": "winery"
  },
  {
    "id": "pittali",
    "name": "Pittali Winery",
    "region": "Agios Theodoros Pitsilias (Limassol)",
    "type": "winery"
  },
  {
    "id": "papaioannou",
    "name": "Papaioannou Winery",
    "region": "Vasa Koilaniou (Limassol)",
    "type": "winery"
  },
  {
    "id": "karseras",
    "name": "Karseras Winery",
    "region": "Kato Platres (Limassol)",
    "type": "winery"
  },
  {
    "id": "evangelou",
    "name": "Evangelou Winery",
    "region": "Pera Pedi (Limassol)",
    "type": "winery"
  },
  {
    "id": "chrysoroyiatissa-winery",
    "name": "Chrysoroyiatissa Winery",
    "region": "Panayia (Paphos)",
    "type": "winery"
  },
  {
    "id": "loel",
    "name": "LOEL Winery",
    "region": "Ayios Silas (Limassol)",
    "type": "winery"
  },
  {
    "id": "etko-olympus",
    "name": "ETKO / Olympus Winery",
    "region": "Omodos (Limassol)",
    "type": "winery"
  },
  {
    "id": "revecca",
    "name": "Revecca Traditional Winery",
    "region": "Agios Mamas (Limassol)",
    "type": "winery"
  },
  {
    "id": "mallia",
    "name": "KEO Mallia Winery",
    "region": "Mallia (Limassol)",
    "type": "winery"
  },
  {
    "id": "monolithos",
    "name": "Monolithos Boutique Winery",
    "region": "Souni (Limassol)",
    "type": "winery"
  },
  {
    "id": "antoniades",
    "name": "M. Antoniades Winery",
    "region": "Mandria (Limassol)",
    "type": "winery"
  },
  {
    "id": "ayios-savas",
    "name": "Ayios Savvas Winery",
    "region": "Agios Tychonas (Limassol)",
    "type": "winery"
  },
  {
    "id": "sodap",
    "name": "SODAP Winery",
    "region": "Limassol",
    "type": "winery"
  },
  {
    "id": "semeli",
    "name": "Semeli Winery",
    "region": "Nicosia",
    "type": "winery"
  },
  {
    "id": "anama",
    "name": "Anama Vintages",
    "region": "Larnaca",
    "type": "winery"
  },
  {
    "id": "solia",
    "name": "Solia Winery",
    "region": "Nicosia",
    "type": "winery"
  },
  {
    "id": "nicolaides",
    "name": "Nicolaides Winery",
    "region": "Pitsilia (Limassol)",
    "type": "winery"
  },
  {
    "id": "dafermou",
    "name": "Ktima Dafermou",
    "region": "Larnaca",
    "type": "winery"
  },
  {
    "id": "zygi-tavernas",
    "name": "Zygi Fish Tavernas",
    "region": "Larnaca",
    "type": "restaurant"
  },
  {
    "id": "governors-beach-tavernas",
    "name": "Governor's Beach Cliff Tavernas",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "the-polo",
    "name": "The Polo",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "the-farmyard",
    "name": "The Farmyard",
    "region": "Kathikas (Paphos)",
    "type": "restaurant"
  },
  {
    "id": "psilo-dendro",
    "name": "Psilo Dendro",
    "region": "Platres",
    "type": "restaurant"
  },
  {
    "id": "polis-harbour",
    "name": "Polis Harbour Tavernas",
    "region": "Paphos",
    "type": "restaurant"
  },
  {
    "id": "cor-gastronomy",
    "name": "Cor Gastronomy",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "sentio",
    "name": "Sentio",
    "region": "Nicosia",
    "type": "restaurant"
  },
  {
    "id": "kakopetria-trout",
    "name": "Kakopetria Trout Tavernas",
    "region": "Troodos",
    "type": "restaurant"
  },
  {
    "id": "kouklia-cafe",
    "name": "Kouklia Village Cafés",
    "region": "Paphos",
    "type": "restaurant"
  },
  {
    "id": "seasons-oriental",
    "name": "Seasons Oriental",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "kiti-tavernas",
    "name": "Kiti Village Tavernas",
    "region": "Larnaca",
    "type": "restaurant"
  },
  {
    "id": "platres-trout",
    "name": "Platres Trout Tavernas",
    "region": "Troodos",
    "type": "restaurant"
  },
  {
    "id": "latsi-harbour",
    "name": "Latsi Harbour Tavernas",
    "region": "Paphos",
    "type": "restaurant"
  },
  {
    "id": "nicosia-tavernas",
    "name": "Nicosia Old Town Tavernas",
    "region": "Nicosia",
    "type": "restaurant"
  },
  {
    "id": "pissouri-tavernas",
    "name": "Pissouri Bay Tavernas",
    "region": "Pissouri (Limassol)",
    "type": "restaurant"
  },
  {
    "id": "omodos-tavernas",
    "name": "Omodos Village Tavernas",
    "region": "Omodos (Limassol)",
    "type": "restaurant"
  },
  {
    "id": "limassol-marina-restaurants",
    "name": "Limassol Marina Restaurants",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "protaras-tavernas",
    "name": "Protaras Tavernas",
    "region": "Famagusta",
    "type": "restaurant"
  },
  {
    "id": "larnaca-old-town",
    "name": "Larnaca Old Town Tavernas",
    "region": "Larnaca",
    "type": "restaurant"
  },
  {
    "id": "pafos-harbour",
    "name": "Pafos Harbour Tavernas",
    "region": "Paphos",
    "type": "restaurant"
  },
  {
    "id": "agros-tavernas",
    "name": "Agros Village Tavernas",
    "region": "Troodos",
    "type": "restaurant"
  },
  {
    "id": "lefkara-tavernas",
    "name": "Lefkara Village Tavernas",
    "nameEl": "Ταβέρνες Λευκάρων",
    "region": "Larnaca",
    "type": "restaurant"
  },
  {
    "id": "kathikas-tavernas",
    "name": "Kathikas Village Tavernas",
    "region": "Paphos",
    "type": "restaurant"
  },
  {
    "id": "limassol-old-town",
    "name": "Limassol Old Town Tavernas",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "kyrenia-tavernas",
    "name": "Kyrenia Harbour Tavernas",
    "region": "Kyrenia",
    "type": "restaurant"
  },
  {
    "id": "ayia-napa-tavernas",
    "name": "Ayia Napa Tavernas",
    "region": "Ayia Napa",
    "type": "restaurant"
  },
  {
    "id": "troodos-square",
    "name": "Troodos Square Cafés",
    "region": "Troodos",
    "type": "restaurant"
  },
  {
    "id": "solea-valley",
    "name": "Solea Valley Tavernas",
    "region": "Troodos",
    "type": "restaurant"
  },
  {
    "id": "zygi-mikri",
    "name": "Zygi Mikri Marina",
    "region": "Larnaca",
    "type": "restaurant"
  },
  {
    "id": "kourion-tavernas",
    "name": "Episkopi & Kourion Tavernas",
    "region": "Limassol",
    "type": "restaurant"
  },
  {
    "id": "artemis",
    "name": "Artemis Trail",
    "nameEl": "Μονοπάτι Αρτέμιδος",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "caledonia-falls",
    "name": "Caledonia Falls",
    "nameEl": "Καταρράκτες Καληδονίας",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "atalante",
    "name": "Atalante Trail",
    "nameEl": "Μονοπάτι Αταλάντης",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "persephone",
    "name": "Persephone Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "olympus-summit",
    "name": "Olympus Summit Trail",
    "nameEl": "Όλυμπος",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "adonis",
    "name": "Adonis Trail",
    "nameEl": "Μονοπάτι Αδώνη",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "aphrodite",
    "name": "Aphrodite Trail",
    "nameEl": "Μονοπάτι Αφροδίτης",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "avakas-gorge",
    "name": "Avakas Gorge",
    "nameEl": "Φαράγγι Αβάκα",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "millomeris-falls",
    "name": "Millomeris Falls",
    "nameEl": "Καταρράκτης Μιλλωμέρη",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "horteri",
    "name": "Horteri Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "cape-greco",
    "name": "Cape Greco Coastal Path",
    "nameEl": "Ακρωτήρι Γκρέκο",
    "region": "Ayia Napa",
    "type": "trail"
  },
  {
    "id": "caledonia-alternative",
    "name": "Caledonia Long Route",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "madari-ridge",
    "name": "Madari Ridge Walk",
    "nameEl": "Μαδάρι",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "petra-tou-romiou",
    "name": "Petra tou Romiou Coastal Walk",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "smigies",
    "name": "Smigies Nature Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "stavros-tis-psokas",
    "name": "Stavros tis Psokas",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "kampos-tou-livadiou",
    "name": "Kampos tou Livadiou",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "pissouromoutti",
    "name": "Pissouromoutti Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "e4-troodos-platres",
    "name": "E4 Troodos Section (Platres–Caledonia)",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "vavatsinia-honeybee",
    "name": "Vavatsinia Honeybee Trail",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "vouni-panagias",
    "name": "Vouni Panagias Nature Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "mnimata-piskopon",
    "name": "Mnimata Piskopon",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "kryos-potamos-loop",
    "name": "Kryos Potamos Valley Walk",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "loumata-ton-aeton",
    "name": "Loumata ton Aeton",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "panagia-tis-amasgou",
    "name": "Panagia tis Amasgou Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "xyliatos-dam",
    "name": "Xyliatos Dam Natural Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "selladi-stavros",
    "name": "Selladi tis Stavros",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "machairas-forest",
    "name": "Machairas Forest Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "horteri-extended",
    "name": "Horteri Extended Loop",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "agia-irini",
    "name": "Agia Irini Gorge",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "livadi-trail",
    "name": "Livadi Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "mylikouri",
    "name": "Mylikouri Nature Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "persephone-extended",
    "name": "Persephone Extended Loop",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "dwarf-oaks",
    "name": "Dwarf Oaks Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "lefkara-path",
    "name": "Lefkara Villages Path",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "potamia-dam",
    "name": "Potamia Dam Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "kionia",
    "name": "Kionia Nature Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "trees-of-woe",
    "name": "Trees of Woe Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "kalidonia-alt",
    "name": "Kalidonia Alternative Route",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "pentadaktylos",
    "name": "Pentadaktylos Foothills",
    "region": "Kyrenia",
    "type": "trail"
  },
  {
    "id": "larnaca-salt-lake",
    "name": "Larnaca Salt Lake Circuit",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "almirolivado",
    "name": "Almirolivado Secret Lake",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "vretsia-roudias",
    "name": "Vretsia – Roudias Venetian Bridge",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "chrysovrysi",
    "name": "Chrysovrysi Natural Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "kavos-trail",
    "name": "Kavos Trail",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "moutti-anemwn",
    "name": "Moutti twn Anemwn",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "politiko-machairas",
    "name": "Politiko to Machairas",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "agia-tilliria",
    "name": "Agia Tilliria",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "ariadni",
    "name": "Ariadni Natural Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "moutti-athasias",
    "name": "Moutti tis Athasias (Cave)",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "gnafkio",
    "name": "Gnafkio Natural Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "panthea",
    "name": "Panthea Natural Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "kionia-profitis-elias",
    "name": "Kionia – Profitis Elias",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "kykkos-konizi",
    "name": "Kykkos to Konizi",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "selladi-trypilos",
    "name": "Selladi tou Staxtou – Trypilos",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "mesa-potamos",
    "name": "Mesa Potamos Waterfall",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "stavrovouni-trail",
    "name": "Stavrovouni Nature Trail",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "agia-varvara-stavrovouni",
    "name": "Agia Varvara to Stavrovouni",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "karvounarka",
    "name": "Karvounarka",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "cape-aspro",
    "name": "Cape Aspro",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "germasogeia-kyparissia",
    "name": "Germasogeia Dam – Kyparissia",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "agioi-anargyroi-circular",
    "name": "Konnos – Agioi Anargyroi",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "sea-caves-anargyroi",
    "name": "Sea Caves – Agioi Anargyroi",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "trooditissa-phini",
    "name": "Trooditissa – Phini",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "prodromos-zoumi",
    "name": "Prodromos – Zoumi",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "prodromos-dam-stavroulia",
    "name": "Prodromos Dam – Stavroulia",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "psilo-dentro-pouziaris",
    "name": "Psilo Dentro – Pouziaris",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "kannoures-agios-nikolaos",
    "name": "Kannoures – Agios Nikolaos Stegis",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "moni-fylagra",
    "name": "Moni – Fylagra",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "konnoi-cyclops",
    "name": "Konnos – Cyclops Cave",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "aphrodite-cape-greco",
    "name": "Aphrodite Trail (Cape Greco)",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "ezousa-valley",
    "name": "Ezousa Valley Walking Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "panagia-araka-stavros",
    "name": "Panagia tou Araka – Stavros tou Agiasmati",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "agiasma",
    "name": "Agiasma Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "arnies",
    "name": "Arnies Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "treis-elies",
    "name": "Treis Elies Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "lemithou",
    "name": "Lemithou Community Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "kastrovounos",
    "name": "Kastrovounos Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "dymes-pelendri",
    "name": "Dymes Pelendri Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "arsos",
    "name": "Arsos Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "kalevounari",
    "name": "Kalevounari Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "germasogeia-weir",
    "name": "Germasogeia Weir Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "agros-kato-mylos",
    "name": "Agros Kato Mylos Trail",
    "region": "Limassol",
    "type": "trail"
  },
  {
    "id": "kalopanagiotis-oikos",
    "name": "Kalopanayiotis Oikos Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "archangelos-mylos-rodous",
    "name": "Archangelos Mylos Tis Rodous Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "lagoudera-agros",
    "name": "Lagoudera Agros Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "lagoudera-madari",
    "name": "Lagoudera/agros Madari Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "polystypos-hazelnut",
    "name": "Polystypos Hazelnut Forest Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "pano-ambelia",
    "name": "Pano Ambelia Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "petros-vanezis",
    "name": "Petros Vanezis Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "gourri",
    "name": "Gourri Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "machairas-lazanias",
    "name": "Machairas Lazanias Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "lazanias-fikardou",
    "name": "Lazanias Fikarou Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "fikardou-archontides",
    "name": "Fikardou Archontides Center Trail",
    "region": "Nicosia",
    "type": "trail"
  },
  {
    "id": "choirokoitia-trail",
    "name": "Choirokoitia Trail",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "panagia-agapis-vavla",
    "name": "Panagia Tis Agapis Vavla Trail",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "lefkara-metamorfoseos",
    "name": "Lefkara Metamorfoseos Tou Sotiros Church Trail",
    "region": "Larnaca",
    "type": "trail"
  },
  {
    "id": "profitis-ilias-konnoi",
    "name": "Profitis Ilias Konnoi Trail",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "panagia-agios-ioannis",
    "name": "Panagia Agios Ioannis Trail",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "panagia-agioi-saranda",
    "name": "Panagia Agioi Saranda Trail",
    "region": "Famagusta",
    "type": "trail"
  },
  {
    "id": "chorteri",
    "name": "Chorteri Nature Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "argakas-dam",
    "name": "Argakas Dam Nature Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "symvoulas",
    "name": "Symvoulas Nature Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "venetian-bridges",
    "name": "Venetian Bridges Trail",
    "region": "Paphos",
    "type": "trail"
  },
  {
    "id": "troodos-visitor-centre",
    "name": "Troodos Visitor Centre Botanical Trail",
    "region": "Troodos",
    "type": "trail"
  },
  {
    "id": "limassol-carnival",
    "name": "Limassol Carnival",
    "nameEl": "Απόκριες Λεμεσού",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "nicosia-winter-festival",
    "name": "Nicosia Winter Festival",
    "region": "Nicosia",
    "type": "event"
  },
  {
    "id": "pafos-xmas-market",
    "name": "Paphos Christmas Market",
    "region": "Paphos",
    "type": "event"
  },
  {
    "id": "commandaria-festival",
    "name": "Commandaria Festival",
    "nameEl": "Γιορτή Κουμανταρίας",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "troodos-ski-season",
    "name": "Troodos Ski Season",
    "nameEl": "Σκι Όλυμπος",
    "region": "Troodos",
    "type": "event"
  },
  {
    "id": "lefkara-lace-festival",
    "name": "Lefkara Lace Festival",
    "region": "Larnaca",
    "type": "event"
  },
  {
    "id": "bellapais-concerts",
    "name": "Bellapais Abbey Concerts",
    "region": "Kyrenia",
    "type": "event"
  },
  {
    "id": "agros-rose-festival-prep",
    "name": "Agros Village Events",
    "region": "Troodos",
    "type": "event"
  },
  {
    "id": "larnaca-xmas-village",
    "name": "Larnaca Christmas Village",
    "region": "Larnaca",
    "type": "event"
  },
  {
    "id": "cyprus-marathon",
    "name": "Cyprus Marathon",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "kakopetria-christmas-village",
    "name": "Kakopetria Christmas Village",
    "region": "Troodos",
    "type": "event"
  },
  {
    "id": "kyperounta-christmas-village",
    "name": "Kyperounta Christmas Village",
    "region": "Troodos",
    "type": "event"
  },
  {
    "id": "ayia-napa-cultural-winter",
    "name": "Agia Napa Cultural Winter",
    "nameEl": "Πολιτιστικός Χειμώνας Αγίας Νάπας",
    "region": "Ayia Napa",
    "type": "event"
  },
  {
    "id": "ayia-napa-winter-swimming",
    "name": "Agia Napa Winter Swimming Festival",
    "region": "Ayia Napa",
    "type": "event"
  },
  {
    "id": "kalopanagiotis-christmas-village",
    "name": "Kalopanagiotis Christmas Village",
    "nameEl": "Χριστουγεννιάτικο Χωριό Καλοπαναγιώτη",
    "region": "Troodos",
    "type": "event"
  },
  {
    "id": "omodos-christmas-market",
    "name": "Omodos Christmas Market",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "lania-christmas",
    "name": "Lania Christmas",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "green-monday",
    "name": "Green Monday",
    "nameEl": "Καθαρά Δευτέρα",
    "region": "All",
    "type": "event"
  },
  {
    "id": "famagusta-carnival",
    "name": "Famagusta Carnival",
    "nameEl": "Καρναβάλι Αμμοχώστου",
    "region": "Paralimni",
    "type": "event"
  },
  {
    "id": "deryneia-christmas-village",
    "name": "Deryneia Christmas Village",
    "nameEl": "Χριστουγεννιάτικο Χωριό Δερύνειας",
    "region": "Famagusta",
    "type": "event"
  },
  {
    "id": "statos-agios-fotios-christmas",
    "name": "Statos–Agios Fotios Christmas Village",
    "region": "Paphos",
    "type": "event"
  },
  {
    "id": "cyprus-jazz-world-music-showcase",
    "name": "Cyprus Jazz & World Music Showcase",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "peloponnese-wine-festival",
    "name": "Peloponnese Wine Festival",
    "region": "Limassol",
    "type": "event"
  },
  {
    "id": "portfolio-wine-tasting",
    "name": "Portfolio Wine Tasting",
    "region": "Paphos",
    "type": "event"
  },
  {
    "id": "protaras-christmas",
    "name": "Protaras Christmas Celebrations",
    "region": "Protaras",
    "type": "event"
  },
  {
    "id": "epiphany-cyprus",
    "name": "Epiphany (Theophania)",
    "nameEl": "Θεοφάνεια",
    "region": "All",
    "type": "event"
  }
];

export const TRAIL_SLUG_TO_ID: Record<string, string> = {
  "artemis-trail": "artemis",
  "atalante-trail": "atalante",
  "persephone-trail": "persephone",
  "adonis-trail": "adonis",
  "aphrodite-trail": "aphrodite",
  "horteri-trail": "horteri",
  "caledonia-long": "caledonia-alternative",
  "smigies-trail": "smigies",
  "pissouromoutti-trail": "pissouromoutti",
  "agia-irini-gorge": "agia-irini",
  "almirolivado-secret-lake": "almirolivado",
  "vretsia-roudias-venetian-bridge": "vretsia-roudias",
  "chrysovrysi-trail": "chrysovrysi",
  "ariadni-trail": "ariadni",
  "moutti-athasias-cave": "moutti-athasias",
  "gnafkio-trail": "gnafkio",
  "panthea-trail": "panthea",
  "ezousa-valley-trail": "ezousa-valley",
  "panagia-araka-stavros-trail": "panagia-araka-stavros",
  "agiasma-trail": "agiasma",
  "arnies-trail": "arnies",
  "treis-elies-trail": "treis-elies",
  "lemithou-trail": "lemithou",
  "kastrovounos-trail": "kastrovounos",
  "dymes-pelendri-trail": "dymes-pelendri",
  "arsos-trail": "arsos",
  "kalevounari-trail": "kalevounari",
  "germasogeia-weir-trail": "germasogeia-weir",
  "agros-kato-mylos-trail": "agros-kato-mylos",
  "kalopanagiotis-oikos-trail": "kalopanagiotis-oikos",
  "archangelos-mylos-rodous-trail": "archangelos-mylos-rodous",
  "lagoudera-agros-trail": "lagoudera-agros",
  "lagoudera-madari-trail": "lagoudera-madari",
  "polystypos-hazelnut-trail": "polystypos-hazelnut",
  "pano-ambelia-trail": "pano-ambelia",
  "petros-vanezis-trail": "petros-vanezis",
  "gourri-trail": "gourri",
  "machairas-lazanias-trail": "machairas-lazanias",
  "lazanias-fikardou-trail": "lazanias-fikardou",
  "fikardou-archontides-trail": "fikardou-archontides",
  "panagia-agapis-vavla-trail": "panagia-agapis-vavla",
  "lefkara-metamorfoseos-trail": "lefkara-metamorfoseos",
  "profitis-ilias-konnoi-trail": "profitis-ilias-konnoi",
  "panagia-agios-ioannis-trail": "panagia-agios-ioannis",
  "panagia-agioi-saranda-trail": "panagia-agioi-saranda",
  "chorteri-trail": "chorteri",
  "argakas-dam-trail": "argakas-dam",
  "symvoulas-trail": "symvoulas",
  "venetian-bridges-trail": "venetian-bridges",
  "troodos-visitor-centre-botanical": "troodos-visitor-centre"
};
